const data = {
  products: [
    {
      _id: '1',
      name: 'Chanel Perfume Ladies',
      slug: 'chanel-perfume-ladies',
      category: 'Perfumes',
      image: '/images/product1.jpg', //679px x 829px
      price: 120,
      countInStock: 10,
      brand: 'Chanel',
      rating: 4.5,
      numReviews: 10,
      description: 'The best perfume from Italy',
      currency: 'USD$',
    },
    {
      _id: '2',
      name: 'Avon Perfume Ladies',
      slug: 'avon-perfume-ladies',
      category: 'Perfumes',
      image: '/images/product2.jpg',
      price: 90,
      countInStock: 20,
      brand: 'Avon',
      rating: 4,
      numReviews: 4,
      description: 'The best perfume for men from Italy',
      currency: 'USD$',
    },
    {
      _id: '3',
      name: 'Lacoste Perfume Man',
      slug: 'lacoste-perfume-man',
      category: 'Perfumes',
      image: '/images/product3.jpg',
      price: 200,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.5,
      numReviews: 10,
      description: 'The best perfume from Italy',
      currency: 'USD$',
    },
    {
      _id: '4',
      name: 'SkinCare Lotion',
      slug: 'skincare-lotion',
      category: 'Lotion',
      image: '/images/product4.jpg',
      price: 94,
      countInStock: 2,
      brand: 'SkinCare',
      rating: 3.5,
      numReviews: 20,
      description: 'The best body lotion for your skin care',
      currency: 'USD$',
    },
    {
      _id: '5',
      name: 'Curology Ladies',
      slug: 'curology-ladies',
      category: 'Roll-on',
      image: '/images/product5.jpg',
      price: 50,
      countInStock: 12,
      brand: 'Curology',
      rating: 5,
      numReviews: 12,
      description: 'Best rollon from Italy',
      currency: 'USD$',
    },
  ],
};
export default data;
